#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void encodeStrings_litStr85_i__nit(void);
void encodeStrings_litStr3_i__nit(void);
void init(void);
void pfract(int len);
void encodeStrings_litStr23_i__nit(void);
void encodeStrings_litStr37_i__nit(void);
int main(int _formal_argc, char **_formal_argv, char **_formal_envp);
void encodeStrings_litStr70_i__nit(void);
void encodeStrings_litStr84_i__nit(void);
void encodeStrings_litStr2_i__nit(void);
void convert(char *line);
void encodeStrings_litStr22_i__nit(void);
void encodeStrings_litStr36_i__nit(void);
void encodeStrings_litStr83_i__nit(void);
void encodeStrings_litStr1_i__nit(void);
void encodeStrings_litStr21_i__nit(void);
void encodeStrings_litStr35_i__nit(void);
void encodeStrings_litStr49_i__nit(void);
int number(char const *p, int len);
void encodeStrings_litStr53_i__nit(void);
typedef long __off_t;
void encodeStrings_litStr67_i__nit(void);
void encodeStrings_litStr82_i__nit(void);
void encodeStrings_litStr0_i__nit(void);
void encodeStrings_litStr20_i__nit(void);
void encodeStrings_litStr19_i__nit(void);
void encodeStrings_litStr34_i__nit(void);
void encodeStrings_litStr48_i__nit(void);
void encodeStrings_litStr52_i__nit(void);
void encodeStrings_litStr66_i__nit(void);
void encodeStrings_litStr81_i__nit(void);
void encodeStrings_litStr18_i__nit(void);
void encodeStrings_litStr33_i__nit(void);
void encodeStrings_litStr47_i__nit(void);
void encodeStrings_litStr51_i__nit(void);
void encodeStrings_litStr80_i__nit(void);
void encodeStrings_litStr65_i__nit(void);
void encodeStrings_litStr79_i__nit(void);
void encodeStrings_litStr32_i__nit(void);
void encodeStrings_litStr17_i__nit(void);
void encodeStrings_litStr46_i__nit(void);
void encodeStrings_litStr50_i__nit(void);
void encodeStrings_litStr64_i__nit(void);
void encodeStrings_litStr78_i__nit(void);
void encodeStrings_litStr31_i__nit(void);
void encodeStrings_litStr16_i__nit(void);
void encodeStrings_litStr45_i__nit(void);
void encodeStrings_litStr59_i__nit(void);
void encodeStrings_litStr63_i__nit(void);
void encodeStrings_litStr77_i__nit(void);
void encodeStrings_litStr9_i__nit(void);
void encodeStrings_litStr30_i__nit(void);
void encodeStrings_litStr15_i__nit(void);
void encodeStrings_litStr44_i__nit(void);
void name3_i__nit(void);
void encodeStrings_litStr29_i__nit(void);
void encodeStrings_litStr58_i__nit(void);
void encodeStrings_litStr62_i__nit(void);
void encodeStrings_litStr76_i__nit(void);
void encodeStrings_litStr8_i__nit(void);
void lflag_i__nit(void);
void encodeStrings_litStr14_i__nit(void);
void encodeStrings_litStr43_i__nit(void);
void name2_i__nit(void);
void encodeStrings_litStr28_i__nit(void);
void encodeStrings_litStr57_i__nit(void);
void encodeStrings_litStr61_i__nit(void);
void encodeStrings_litStr75_i__nit(void);
void encodeStrings_litStr7_i__nit(void);
void megaInit(void);
void encodeStrings_litStr13_i__nit(void);
void encodeStrings_litStr27_i__nit(void);
void encodeStrings_litStr42_i__nit(void);
void name1_i__nit(void);
void encodeStrings_litStr56_i__nit(void);
void encodeStrings_litStr60_i__nit(void);
void encodeStrings_litStr74_i__nit(void);
void encodeStrings_litStr88_i__nit(void);
void encodeStrings_litStr6_i__nit(void);
void encodeStrings_litStr12_i__nit(void);
void encodeStrings_litStr41_i__nit(void);
void encodeStrings_litStr26_i__nit(void);
void encodeStrings_litStr55_i__nit(void);
void encodeStrings_litStr69_i__nit(void);
void encodeStrings_litStr73_i__nit(void);
void encodeStrings_litStr87_i__nit(void);
void encodeStrings_litStr5_i__nit(void);
void encodeStrings_litStr11_i__nit(void);
void encodeStrings_litStr40_i__nit(void);
void encodeStrings_litStr25_i__nit(void);
void encodeStrings_litStr54_i__nit(void);
void encodeStrings_litStr39_i__nit(void);
void encodeStrings_litStr68_i__nit(void);
void encodeStrings_litStr72_i__nit(void);
void encodeStrings_litStr86_i__nit(void);
void encodeStrings_litStr4_i__nit(void);
int unit(int len, char const *p);
void encodeStrings_litStr10_i__nit(void);
void encodeStrings_litStr24_i__nit(void);
void encodeStrings_litStr38_i__nit(void);
void encoder(int n, char str[]);
void encodeStrings_litStr71_i__nit(void);
extern int lflag;
extern char *name3[22];
extern char *name2[10];
extern char *name1[20];
extern char **_global_argv;
extern int _global_argc;
extern char **_global_envp;
extern char encodeStrings_litStr32[8];
extern char encodeStrings_litStr31[8];
extern char encodeStrings_litStr30[9];
extern char encodeStrings_litStr29[9];
extern char encodeStrings_litStr28[7];
extern char encodeStrings_litStr27[7];
extern char encodeStrings_litStr26[4];
extern char encodeStrings_litStr25[5];
extern char encodeStrings_litStr24[6];
extern char encodeStrings_litStr23[6];
extern char encodeStrings_litStr22[4];
extern char encodeStrings_litStr21[5];
extern char encodeStrings_litStr20[5];
extern char encodeStrings_litStr19[6];
extern char encodeStrings_litStr18[4];
extern char encodeStrings_litStr17[4];
extern char encodeStrings_litStr16[1];
extern char encodeStrings_litStr15[2];
extern char encodeStrings_litStr14[7];
extern char encodeStrings_litStr13[3];
extern char encodeStrings_litStr12[1];
extern char encodeStrings_litStr11[2];
extern char encodeStrings_litStr10[8];
extern char encodeStrings_litStr9[1];
extern char encodeStrings_litStr8[2];
extern char encodeStrings_litStr7[2];
extern char encodeStrings_litStr6[2];
extern char encodeStrings_litStr5[8];
extern char encodeStrings_litStr4[2];
extern char encodeStrings_litStr3[2];
extern char encodeStrings_litStr2[34];
extern char encodeStrings_litStr1[34];
extern char encodeStrings_litStr0[20];
extern char encodeStrings_litStr88[3];
extern char encodeStrings_litStr87[6];
extern char encodeStrings_litStr86[3];
extern char encodeStrings_litStr85[2];
extern char encodeStrings_litStr84[6];
extern char encodeStrings_litStr83[3];
extern char encodeStrings_litStr82[2];
extern char encodeStrings_litStr81[10];
extern char encodeStrings_litStr80[13];
extern char encodeStrings_litStr79[9];
extern char encodeStrings_litStr78[9];
extern char encodeStrings_litStr77[5];
extern char encodeStrings_litStr76[1];
extern char encodeStrings_litStr75[3];
extern char encodeStrings_litStr74[4];
extern char encodeStrings_litStr73[3];
extern char encodeStrings_litStr72[3];
extern char encodeStrings_litStr71[2];
extern char encodeStrings_litStr70[11];
extern char encodeStrings_litStr69[5];
extern char encodeStrings_litStr68[16];
extern char encodeStrings_litStr67[13];
extern char encodeStrings_litStr66[15];
extern char encodeStrings_litStr65[14];
extern char encodeStrings_litStr64[16];
extern char encodeStrings_litStr63[13];
extern char encodeStrings_litStr62[14];
extern char encodeStrings_litStr61[18];
extern char encodeStrings_litStr60[13];
extern char encodeStrings_litStr59[13];
extern char encodeStrings_litStr58[12];
extern char encodeStrings_litStr57[10];
extern char encodeStrings_litStr56[10];
extern char encodeStrings_litStr55[10];
extern char encodeStrings_litStr54[11];
extern char encodeStrings_litStr53[11];
extern char encodeStrings_litStr52[12];
extern char encodeStrings_litStr51[12];
extern char encodeStrings_litStr50[9];
extern char encodeStrings_litStr49[8];
extern char encodeStrings_litStr48[8];
extern char encodeStrings_litStr47[9];
extern char encodeStrings_litStr46[8];
extern char encodeStrings_litStr45[7];
extern char encodeStrings_litStr44[7];
extern char encodeStrings_litStr43[8];
extern char encodeStrings_litStr42[6];
extern char encodeStrings_litStr41[6];
extern char encodeStrings_litStr40[6];
extern char encodeStrings_litStr38[7];
extern char encodeStrings_litStr38[7];
extern char encodeStrings_litStr37[4];
extern char encodeStrings_litStr36[1];
extern char encodeStrings_litStr35[9];
extern char encodeStrings_litStr34[9];
extern char encodeStrings_litStr33[10];
extern char encodeStrings_litStr39[7];
