#include <stdio.h>
#include <stdlib.h>

extern void init_matrix(void) ;
extern void encodeStrings_litStr2_i__nit(void) ;
extern void encodeStrings_litStr5_i__nit(void) ;
extern void encodeStrings_litStr8_i__nit(void) ;
extern void disp_matrix(void) ;
extern int main(int _formal_argc , char **_formal_argv , char **_formal_envp ) ;
extern void encodeStrings_litStr0_i__nit(void) ;
extern void get_computer_move(void) ;
extern void megaInit(void) ;
extern void encodeStrings_litStr3_i__nit(void) ;
extern void encodeStrings_litStr6_i__nit(void) ;
extern void encodeStrings_litStr10_i__nit(void) ;
extern void get_player_move(void) ;
extern void encodeStrings_litStr9_i__nit(void) ;
extern void encodeStrings_litStr1_i__nit(void) ;
extern void encodeStrings_litStr4_i__nit(void) ;
extern void encoder(int n , char str[] ) ;
extern void encodeStrings_litStr7_i__nit(void) ;
extern void matrix_i__nit(void) ;
extern char check(void) ;
extern char **_global_argv;
extern int _global_argc;
extern char **_global_envp;
extern char matrix[3][3] ;
extern char encodeStrings_litStr10[11] ;
extern long _4entropy;
extern long _4alwaysZero;
extern char encodeStrings_litStr9[10] ;
extern char encodeStrings_litStr8[43] ;
extern char encodeStrings_litStr7[34] ;
extern char encodeStrings_litStr6[26] ;
extern char encodeStrings_litStr5[8] ;
extern char encodeStrings_litStr4[38] ;
extern char encodeStrings_litStr3[6] ;
extern char encodeStrings_litStr2[2] ;
extern int _5_check__opaque_array[30];
extern char encodeStrings_litStr1[14] ;
extern char encodeStrings_litStr0[15] ;
